# Generated by Django 2.1 on 2019-05-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='copmplte',
            new_name='complete',
        ),
    ]
